In [ ]:
# Numpy basics
!pip install numpy

In [3]:
import numpy as np


In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
## array generation function
arr = np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [9]:
arr = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr = np.linspace(1,5,5) #linear space ke liye
arr

array([1., 2., 3., 4., 5.])

In [11]:
## Random generation function
arr = np.random.rand(10)
arr

array([0.44549782, 0.08692264, 0.24579221, 0.04695345, 0.70248228,
       0.38441153, 0.87716871, 0.62452506, 0.53684427, 0.15363724])

Jab ak square bracket me ho toh usko hm vactor bolte hai agr double bracket me ho toh usko matrix  like this [[]] 

In [12]:
#Standardization me sab value dega
arr = np.random.randn(10)
arr

array([ 1.18409201,  0.09346031, -1.41961616,  1.30504722, -0.52380352,
        0.22398126,  0.19685585, -1.59042637, -0.07897262, -1.02668273])

In [13]:
## Ye 6 tak koi random number generate kr ke dega
arr = np.random.randint(6)
arr

1

In [14]:
# 10 se 20 tak 10 random number generate karega
arr = np.random.randint(10,20,10)
arr

array([19, 16, 18, 14, 12, 11, 17, 17, 19, 16])

In [15]:
## Introduce array attribute
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
## Shape pta krna hai toh shape ke aage bracket nhi lgaya jata hai qki wo attribute hai 
arr.shape

(3, 4)

In [17]:
arr.size

12

In [18]:
arr.dtype

dtype('int32')

In [19]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arr.min()

1

In [21]:
arr.max()

12

In [22]:
arr.sum()

78

In [ ]:
#  it give us column wise sum
np.sum(arr,axis =0)


array([15, 18, 21, 24])

In [ ]:
#  it give us row wise sum
np.sum(arr,axis=1)

array([10, 26, 42])

In [26]:
#  it give us middle value
arr.mean()

6.5

In [ ]:
#  it give us standard deviation
arr.std()

3.452052529534663

In [ ]:
#  it give us maximum nuber index
arr.argmax()

11

In [ ]:
#  it give us minimum number index
arr.argmin()

0

In [30]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])