In [2]:
import numpy as np

In [ ]:
# Add two array  arr ka size same hona chahiye
#  All operation are performed in array
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2
a1 - a2
a1 * a2
a1 / a2
a1 // a2
a1 ** a2

array([ 6, 14, 24, 36, 50])

In [ ]:
#  Broadcasting
l = [10,20,30,40,50]
arr = np.array(l)
arr + 10


array([20, 30, 40, 50, 60])

In [10]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [13]:
a = np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
# Shallow copy jaise hm array me koi operation kiya toh toh wo original wla me nhi show hoga
slice  = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
# a.copy() likhne se kuch nhi aayega a me.
#  Deep copy
a
b = a
b[0] = 99

In [19]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [20]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A

array([[1, 2],
       [3, 4]])

In [22]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# Multiply A matrix to B matrix using @
A@B

array([[19, 22],
       [43, 50]])

In [24]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
#  Transpose of a matrix
A.T

array([[1, 3],
       [2, 4]])

In [26]:
A

array([[1, 2],
       [3, 4]])

In [27]:
B

array([[5, 6],
       [7, 8]])

In [29]:
# Stcking array
# cannot stack two matrix
# there are three types of stcking 
# vertical stack, horizontal stack, normal stack

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.vstack((a,b))



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [30]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [32]:
# Spiliting array
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
a = np.hsplit(c,2)
a

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
a = np.vsplit(c,2)
a

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [38]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
