In [1]:
import numpy as np

In [3]:
# Valid Sudoku
# Har row or column ka sum 45 hona chahiye (1 to 9 ka sum)
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [7]:
row_sum = np.sum(s, axis= 1) # sum ke liye row axis 1 hoga 
row_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [9]:
column_sum = np.sum(s, axis = 0) # sum ke liye column axis 0 hoga 
column_sum

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [12]:
slice = s [0:3,0:3] # subgrid
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [13]:
slice = s[0:3, 3:6] #Subgrid
slice

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [16]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [18]:
#Columns: [Age, Math marks, Science marks]
data = np.array([
    [18, 85, 78],#Student 1
    [19, 92, 88],#Student 2
    [17, 76, 95],#Student 3
    [18, 65, 70],#Student 4
    [20, 90, 85] #Student 5
])

In [20]:
# Get the shape of the matrix
data.shape

(5, 3)

In [25]:
#Find the average of students.
mean = np.mean(data[:,0])
mean

18.4

In [27]:
# extract the math marks of all students.
math=data[:,1]
math

array([85, 92, 76, 65, 90])

In [28]:
# Find the highest Science marks.
science = np.max(data[0:,2])
science

95

In [30]:
# Get details of the students who scored more than 90 in math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [32]:
##Increase math marks of all students by 5.
data = data[:,1] +5
data

array([ 95, 102,  86,  75, 100])

In [38]:
data = np.array([
    [18, 85, 78],#Student 1
    [19, 92, 88],#Student 2
    [17, 76, 95],#Student 3
    [18, 65, 70],#Student 4
    [20, 90, 85] #Student 5
])

In [40]:
# Find how many students are younger than 19
len([data[:,0] < 19])


1

In [42]:
# Calculate the average marks in each subject (colum-wise mean)
np.mean(data[:,1:], axis =0)

array([81.6, 83.2])

In [44]:
# Get data of student who scored  at least 80 in both  subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [45]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [54]:
data = np.array([
    [18, 85, 78],#Student 1
    [19, 92, 88],#Student 2
    [17, 76, 95],#Student 3
    [18, 65, 70],#Student 4
    [20, 90, 85] #Student 5
])

In [55]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [57]:
# Replace all science marks < 75 with 0
data[:,2][data[:,2]<75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])