In [1]:
import numpy as np

In [2]:
#  np.arange it create array
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#  it returns the index value 
arr[6]

17

In [4]:
arr[1:5]
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# last wla value step hota hai
arr[1::2]

array([12, 14, 16, 18, 20])

In [6]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#  it give us row wise element
arr[1]

array([ 6,  7,  8,  9, 10])

In [10]:
arr[0][0]

1

In [11]:
arr[0][4]

5

In [12]:
arr[5][4]

30

In [15]:
# slicing puri row or puri column ko
slice = arr[0:2,1:3]
slice


array([[2, 3],
       [7, 8]])

In [16]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
#  it give us only column no pass value of row
slice = arr[:,3]
slice

array([ 4,  9, 14, 19, 24, 29])

In [25]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])